# Generated by Django 4.1 on 2022-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category_resumeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='category',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
