# Generated by Django 4.1 on 2022-08-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='client',
            new_name='percentage',
        ),
    ]
