# Generated by Django 4.1 on 2022-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_client_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='github_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
